# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-06 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareparts',
            name='ImagePart',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='spareparts/'),
            preserve_default=False,
        ),
    ]
