# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-06 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_spareparts_imagepart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spareparts',
            old_name='NamePart',
            new_name='namePart',
        ),
    ]
