# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-06 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_auto_20191106_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcategory',
            name='spareParts',
        ),
        migrations.AddField(
            model_name='spareparts',
            name='carCat',
            field=models.ManyToManyField(to='carapp.CarCategory'),
        ),
    ]
