# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_auto_20191106_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('sparepart', models.ManyToManyField(blank=True, to='carapp.SpareParts')),
            ],
        ),
    ]
