# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-07 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sparepart',
        ),
        migrations.AddField(
            model_name='spareparts',
            name='sparepart',
            field=models.ManyToManyField(blank=True, to='carapp.Cart'),
        ),
    ]
