# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-07 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0007_auto_20191107_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='sparepart',
            new_name='sparePart',
        ),
    ]
